{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whoogle.fullname" . }}
  labels:
    {{- include "whoogle.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.config | quote }}
{{- end }}
